"""Post-FMMT denoising research, including retained historical controls."""

from .affine_relation_transport import (
    RelationResolution,
    denoise_affine_relations,
)
from .cross_predictive_transport import (
    CrossPredictiveResolution,
    action_contracting_connection_readout_forms,
    action_contracting_connection_transport_1d,
    debiased_transport_coefficient,
    denoise_cross_predictive_transport,
    relation_scale_transport,
)
from .cross_predictive_transport_2d import (
    CrossPredictive2DResolution,
    denoise_cross_predictive_transport_2d,
    heldout_relation_characteristic_measure_2d,
    heldout_relation_characteristic_population_2d,
    heldout_relation_transport_metric_2d,
    relation_characteristic_measure_2d,
    relation_characteristic_population_2d,
    relation_transport_metric_2d,
)
from .causal_ancestry import (
    CausalAncestry,
    shared_label_causal_forest,
    shared_label_continuous_causal_forest,
    transport_causal_ancestry,
)
from .causal_parity_transport import (
    denoise_causal_parity_transport,
    parity_root_pixels,
)
from .causal_predictive_geometry import (
    causal_predictive_fixed_point,
    causal_parity_predictive_geometry,
    weighted_quantile_particles,
)
from .fused_transport_geometry import (
    combine_information_geometries,
    domain_unit_precision,
    extract_causal_support,
    observation_graph_measure,
    predictive_directional_jet_sasaki_geometry,
    predictive_horizontal_wasserstein_geometry,
    predictive_information_geometry,
    predictive_jet_horizontal_wasserstein_geometry,
    predictive_lineage_jet_geometry,
    predictive_wasserstein_geometry,
    weighted_empirical_quantiles,
    weighted_support_quantiles,
)
from .continuous_source_transport import (
    ContinuousSourceResolution,
    denoise_continuous_source_transport,
    selling_decomposition,
    source_measure_operator,
)
from .fabada_oracle import (
    denoise_oracle_fabada_1d,
    denoise_oracle_fabada_from_corruption_1d,
    oracle_corruption_moments_1d,
    reflected_mean_operator_1d,
)
from .crossfit_characteristic_transport_2d import (
    crossfit_characteristic_measure_2d,
    crossfit_characteristic_population_2d,
    denoise_crossfit_characteristic_transport_2d,
    primitive_directions_2d,
    primitive_direction_weights_2d,
)
from .witnessed_characteristic_transport_2d import (
    dense_characteristic_proposals_2d,
    denoise_joint_characteristic_transport_2d,
    denoise_joint_authority_transport_2d,
    denoise_joint_source_authority_transport_2d,
    denoise_joint_overlap_covariance_transport_2d,
    denoise_joint_lineage_covariance_transport_2d,
    joint_characteristic_measure_2d,
    joint_characteristic_population_2d,
    lineage_joint_characteristic_measure_2d,
    lineage_joint_characteristic_population_2d,
    transported_lineage_joint_characteristic_measure_2d,
    transported_lineage_joint_characteristic_population_2d,
    witnessed_characteristic_measure_2d,
    witnessed_characteristic_population_2d,
)
from .transport_support import (
    TransportResolution,
    denoise_1d,
    denoise_2d_fmmt,
    support_density,
    transport_support_birth,
)
from .continuous_tangent_transport_2d import (
    continuous_tangent_joint_measure_2d,
    continuous_tangent_joint_population_2d,
    continuous_tangent_jet_field_2d,
    continuous_tangent_jet_particles_2d,
    continuous_tangent_jet_projection_2d,
    continuous_tangent_proposals_2d,
    continuous_tangent_signal_population_2d,
    denoise_continuous_tangent_lineage_covariance_2d,
    uniform_projective_tangents,
)
from .causal_tangent_atlas_2d import continuous_tangent_causal_atlas_2d
from .causal_information_lineage_2d import (
    causal_information_lineage_law_2d,
    causal_information_lineage_readouts_2d,
    causal_information_phase_integrated_law_2d,
    causal_information_phase_integrated_readouts_2d,
    causal_information_phase_refinement_readouts_2d,
    nested_population_phases,
)
from .continual_eikonal_noise_transport_2d import (
    ContinualEikonalResolution,
    continual_transport_metric,
    denoise_continual_eikonal_noise_transport_2d,
    directional_noise_witnesses,
    phase_covector_noise_authority,
    phase_covector_sufficient_statistics,
)
from .continual_fabada_eikonal_2d import (
    denoise_anisotropic_moment_residual_posterior_2d,
    denoise_bounded_complete_moment_posterior_2d,
    denoise_complete_moment_residual_posterior_2d,
    denoise_continual_fabada_eikonal_2d,
    denoise_continual_residual_posterior_2d,
)
from .canonical_variance_transport_2d import (
    crossfit_variance_law,
    denoise_canonical_variance_transport_2d,
    variance_coordinate,
)
from .backward_moment_smoother_2d import (
    denoise_backward_moment_smoother_2d,
    diagonal_backward_gain,
)
from .reflection_consistent_posterior_2d import (
    denoise_reflection_consistent_posterior_2d,
    reflection_consistency_authority,
)
from .zero_residual_component_2d import (
    phase_integrated_zero_residual_component_family_2d,
    phase_integrated_zero_residual_components_2d,
    zero_residual_component_readouts,
)
from .cross_chart_transport_closure_2d import (
    cross_chart_transport_closure_readout,
    denoise_cross_chart_transport_closure_2d,
)
from .continuous_tangent_source_geometry_2d import (
    continuous_tangent_source_geometry_2d,
)
from .typical_orbit_set import (
    LocalOrbitResolution,
    TypicalOrbitResolution,
    denoise_local_orbit_survival,
    denoise_typical_orbit_set,
    fmmt_local_coherence_veto,
    infer_local_orbit_survival,
    infer_typical_orbit_set,
)

__all__ = [
    "CausalAncestry",
    "RelationResolution",
    "CrossPredictiveResolution",
    "CrossPredictive2DResolution",
    "ContinuousSourceResolution",
    "ContinualEikonalResolution",
    "LocalOrbitResolution",
    "TypicalOrbitResolution",
    "TransportResolution",
    "denoise_affine_relations",
    "denoise_cross_predictive_transport",
    "action_contracting_connection_readout_forms",
    "action_contracting_connection_transport_1d",
    "denoise_cross_predictive_transport_2d",
    "heldout_relation_characteristic_measure_2d",
    "heldout_relation_characteristic_population_2d",
    "heldout_relation_transport_metric_2d",
    "denoise_causal_parity_transport",
    "denoise_continuous_source_transport",
    "denoise_continual_eikonal_noise_transport_2d",
    "denoise_continual_fabada_eikonal_2d",
    "denoise_continual_residual_posterior_2d",
    "denoise_complete_moment_residual_posterior_2d",
    "denoise_anisotropic_moment_residual_posterior_2d",
    "denoise_bounded_complete_moment_posterior_2d",
    "crossfit_variance_law",
    "denoise_canonical_variance_transport_2d",
    "variance_coordinate",
    "denoise_backward_moment_smoother_2d",
    "diagonal_backward_gain",
    "denoise_reflection_consistent_posterior_2d",
    "reflection_consistency_authority",
    "zero_residual_component_readouts",
    "phase_integrated_zero_residual_components_2d",
    "phase_integrated_zero_residual_component_family_2d",
    "cross_chart_transport_closure_readout",
    "denoise_cross_chart_transport_closure_2d",
    "denoise_oracle_fabada_1d",
    "denoise_oracle_fabada_from_corruption_1d",
    "denoise_crossfit_characteristic_transport_2d",
    "causal_parity_predictive_geometry",
    "causal_predictive_fixed_point",
    "debiased_transport_coefficient",
    "combine_information_geometries",
    "domain_unit_precision",
    "extract_causal_support",
    "observation_graph_measure",
    "oracle_corruption_moments_1d",
    "predictive_directional_jet_sasaki_geometry",
    "predictive_information_geometry",
    "predictive_horizontal_wasserstein_geometry",
    "predictive_jet_horizontal_wasserstein_geometry",
    "predictive_lineage_jet_geometry",
    "predictive_wasserstein_geometry",
    "weighted_empirical_quantiles",
    "weighted_support_quantiles",
    "relation_scale_transport",
    "relation_characteristic_measure_2d",
    "relation_characteristic_population_2d",
    "relation_transport_metric_2d",
    "reflected_mean_operator_1d",
    "parity_root_pixels",
    "denoise_1d",
    "denoise_2d_fmmt",
    "support_density",
    "shared_label_causal_forest",
    "shared_label_continuous_causal_forest",
    "selling_decomposition",
    "continual_transport_metric",
    "directional_noise_witnesses",
    "phase_covector_noise_authority",
    "phase_covector_sufficient_statistics",
    "source_measure_operator",
    "crossfit_characteristic_measure_2d",
    "crossfit_characteristic_population_2d",
    "primitive_directions_2d",
    "primitive_direction_weights_2d",
    "dense_characteristic_proposals_2d",
    "denoise_joint_characteristic_transport_2d",
    "denoise_joint_authority_transport_2d",
    "denoise_joint_source_authority_transport_2d",
    "denoise_joint_overlap_covariance_transport_2d",
    "denoise_joint_lineage_covariance_transport_2d",
    "joint_characteristic_measure_2d",
    "joint_characteristic_population_2d",
    "lineage_joint_characteristic_measure_2d",
    "lineage_joint_characteristic_population_2d",
    "transported_lineage_joint_characteristic_measure_2d",
    "transported_lineage_joint_characteristic_population_2d",
    "witnessed_characteristic_measure_2d",
    "witnessed_characteristic_population_2d",
    "transport_causal_ancestry",
    "transport_support_birth",
    "weighted_quantile_particles",
    "continuous_tangent_joint_measure_2d",
    "continuous_tangent_joint_population_2d",
    "continuous_tangent_jet_field_2d",
    "continuous_tangent_jet_particles_2d",
    "continuous_tangent_jet_projection_2d",
    "continuous_tangent_proposals_2d",
    "continuous_tangent_signal_population_2d",
    "denoise_continuous_tangent_lineage_covariance_2d",
    "uniform_projective_tangents",
    "continuous_tangent_causal_atlas_2d",
    "causal_information_lineage_law_2d",
    "causal_information_lineage_readouts_2d",
    "causal_information_phase_integrated_law_2d",
    "causal_information_phase_integrated_readouts_2d",
    "causal_information_phase_refinement_readouts_2d",
    "nested_population_phases",
    "continuous_tangent_source_geometry_2d",
    "denoise_local_orbit_survival",
    "denoise_typical_orbit_set",
    "fmmt_local_coherence_veto",
    "infer_local_orbit_survival",
    "infer_typical_orbit_set",
]
