"""Stable apply_window candidate for QHSO: modular-chirp recurrence.

This file replaces the unstable dense Dirichlet separator

    Sep_L(Y)[k] = (1/M) sum_q Y[q] D_L(k/T - q/M)

with the equivalent coefficient-window evaluation:

    c = ifft_M(Y)
    out[k] = sum_{n=0}^{L-1} c[n] exp(-2*pi*i*k*n/T)

The evaluation is done by Bluestein's identity, but the chirps are generated by
an exact integer recurrence for n^2 mod 2T.  The naive formula exp(±pi*i*n*n/T)
causes phase drift and gives ~1e-13 at T≈4096.  The modular recurrence keeps the
phase table periodic exactly in integer arithmetic before the final sin/cos.

This is not the dense sidecar recurrence.  It is the stable recurrence currently
available for apply_window.  It can be routed real-only by carrying real and
imaginary planes separately through the existing real power-of-two convolution
kernel.
"""
from __future__ import annotations

import csv
import math
from dataclasses import dataclass
import numpy as np


def next_pow2(n: int) -> int:
    return 1 << ((n - 1).bit_length())


def modular_chirps(T: int) -> tuple[np.ndarray, np.ndarray]:
    """Return ca[n]=exp(-pi*i*n^2/T), cb[n]=exp(+pi*i*n^2/T), n=0..T-1.

    n^2 is reduced modulo 2T before phase generation.  This is the critical
    recurrence; it enforces the exact periodicity of the chirp in double.
    """
    n = np.arange(T, dtype=np.int64)
    r = (n * n) % (2 * T)
    ang = np.pi * (r.astype(np.float64) / float(T))
    co = np.cos(ang)
    si = np.sin(ang)
    return co - 1j * si, co + 1j * si


def modular_chirps_recurrence(T: int) -> tuple[np.ndarray, np.ndarray]:
    """Same chirps as modular_chirps, generated by r_{n+1}=r_n+2n+1 mod 2T."""
    r = np.empty(T, dtype=np.int64)
    cur = 0
    for n in range(T):
        r[n] = cur
        cur = (cur + 2 * n + 1) % (2 * T)
    ang = np.pi * (r.astype(np.float64) / float(T))
    co = np.cos(ang)
    si = np.sin(ang)
    return co - 1j * si, co + 1j * si


def apply_window_coeffs_modchirp(c: np.ndarray, T: int) -> np.ndarray:
    """Evaluate sum_{n=0}^{L-1} c[n] exp(-2*pi*i*k*n/T), k=0..T-1.

    c may have length L <= T.  Missing coefficients are zero.  The transform is
    a length-T DFT of the zero-padded coefficient window, implemented by stable
    modular Bluestein.
    """
    c = np.asarray(c, dtype=np.complex128)
    L = c.size
    if L > T:
        raise ValueError("window length L must be <= target length T")
    if T == 1:
        return np.array([c[0] if L else 0.0], dtype=np.complex128)
    a_chirp, b_chirp = modular_chirps_recurrence(T)
    C = next_pow2(2 * T - 1)
    a = np.zeros(C, dtype=np.complex128)
    b = np.zeros(C, dtype=np.complex128)
    a[:L] = c * a_chirp[:L]
    b[:T] = b_chirp
    b[C - T + 1 :] = b_chirp[1:][::-1]
    conv = np.fft.ifft(np.fft.fft(a) * np.fft.fft(b))[:T]
    return conv * a_chirp


def apply_window_from_carrier_modchirp(Y: np.ndarray, L: int, T: int) -> np.ndarray:
    """Stable apply_window(L,Y,T,M) by coefficient recovery + modular chirp eval."""
    Y = np.asarray(Y, dtype=np.complex128)
    M = Y.size
    c = np.fft.ifft(Y)
    return apply_window_coeffs_modchirp(c[:L], T)


def direct_dft_matrix_eval(c: np.ndarray, T: int) -> np.ndarray:
    c = np.asarray(c, dtype=np.complex128)
    n = np.arange(c.size)[None, :]
    k = np.arange(T)[:, None]
    return np.exp(-2j * np.pi * k * n / T) @ c


def self_check_small() -> None:
    rng = np.random.default_rng(0)
    for T in range(2, 128):
        for L in [1, min(2, T), max(1, T // 3), T]:
            c = rng.standard_normal(L) + 1j * rng.standard_normal(L)
            got = apply_window_coeffs_modchirp(c, T)
            ref = direct_dft_matrix_eval(c, T)
            err = np.linalg.norm(got - ref) / max(np.linalg.norm(ref), 1.0)
            if err > 5e-14:
                raise AssertionError((T, L, err))


if __name__ == "__main__":
    self_check_small()
    print("small checks ok")
