"""Suzuki's arithmetic kernel, with float and high-precision reference paths."""
from __future__ import annotations

from functools import lru_cache
import math
import numpy as np
import mpmath as mp
from scipy.special import gamma, hyp2f1


def xi(s):
    s = mp.mpc(s)
    return mp.mpf("0.5") * s * (s - 1) * mp.power(mp.pi, -s / 2) * mp.gamma(s / 2) * mp.zeta(s)


def theta_omega_direct(omega, z):
    w, z = mp.mpf(omega), mp.mpc(z)
    return xi(mp.mpf("0.5") - w - 1j * z) / xi(mp.mpf("0.5") + w - 1j * z)


@lru_cache(maxsize=None)
def _prime_factors(n: int):
    factors = []
    p = 2
    while p * p <= n:
        if n % p == 0:
            factors.append(p)
            while n % p == 0:
                n //= p
        p += 1 if p == 2 else 2
    if n > 1:
        factors.append(n)
    return tuple(factors)


@lru_cache(maxsize=None)
def c_omega_cached(omega_text: str, n: int):
    w = mp.mpf(omega_text)
    ans = mp.power(n, w)
    for p in _prime_factors(n):
        ans *= 1 - mp.power(p, -2 * w)
    return ans


def c_omega(omega, n: int):
    return c_omega_cached(mp.nstr(mp.mpf(omega), 50), int(n))


def _tail_beta_mp(w, x):
    # Integral from x^2 to 1, after y=1-t. This form avoids an endpoint
    # singularity at t=1 and remains valid when 3/2-w is non-positive.
    q = 1 - x * x
    return mp.power(q, w) / w * mp.hyp2f1(w, w - mp.mpf("0.5"), w + 1, q)


def g_omega_mp(omega, x):
    w, x = mp.mpf(omega), mp.mpf(x)
    if x <= 0 or x >= 1:
        return mp.mpf("0")
    q = 1 - x * x
    integral = _tail_beta_mp(w, x)
    return 2 * mp.power(mp.pi, w) / mp.gamma(w) * (
        mp.power(x, 2 - w) * mp.power(q, w - 1)
        - w * mp.power(x, w - 1) * integral)


def g_omega(omega, x):
    """Vectorized double-precision g; high precision is g_omega_mp."""
    w = float(omega)
    a = np.asarray(x, dtype=float)
    scalar = a.ndim == 0
    a = np.atleast_1d(a)
    out = np.zeros_like(a)
    mask = (a > 0.0) & (a < 1.0)
    xx = a[mask]
    q = 1.0 - xx * xx
    integ = q ** w / w * hyp2f1(w, w - 0.5, w + 1.0, q)
    out[mask] = 2.0 * math.pi ** w / gamma(w) * (
        xx ** (2.0 - w) * q ** (w - 1.0)
        - w * xx ** (w - 1.0) * integ)
    return float(out[0]) if scalar else out


def h_omega_mp(omega, x):
    w, x = mp.mpf(omega), mp.mpf(x)
    if x <= 1:
        return mp.mpf("0")
    return mp.fsum(c_omega(w, n) * g_omega_mp(w, n / x)
                   for n in range(1, int(mp.floor(x)) + 1)) / x


def h_omega(omega, x):
    w = float(omega)
    a = np.asarray(x, dtype=float)
    scalar = a.ndim == 0
    a = np.atleast_1d(a)
    out = np.zeros_like(a)
    for i, xx in enumerate(a):
        if xx <= 1.0:
            continue
        total = 0.0
        for n in range(1, int(math.floor(xx)) + 1):
            total += float(c_omega(w, n)) * g_omega(w, n / xx)
        out[i] = total / xx
    return float(out[0]) if scalar else out


def k_omega(omega, r):
    a = np.asarray(r, dtype=float)
    scalar = a.ndim == 0
    a = np.atleast_1d(a)
    out = np.zeros_like(a)
    mask = a > 0.0
    out[mask] = np.exp(a[mask] / 2.0) * h_omega(omega, np.exp(a[mask]))
    return float(out[0]) if scalar else out


def k_omega_mp(omega, r):
    r = mp.mpf(r)
    return mp.mpf("0") if r <= 0 else mp.exp(r / 2) * h_omega_mp(omega, mp.exp(r))


def mellin_from_arithmetic(omega, z):
    """Termwise Mellin transform of c*g, evaluated at high precision.

    This stays on the arithmetic construction path: the g transform is
    quadrature-evaluated, while the Dirichlet series generated by c_omega is
    evaluated through its proven Euler product zeta ratio.
    """
    w, z = mp.mpf(omega), mp.mpc(z)
    s = mp.mpf("0.5") - 1j * z
    # Fubini on the defining integral gives this beta expression. It avoids
    # catastrophic cancellation in g(t) as t approaches zero.
    beta = mp.beta((s + 2 - w) / 2, w)
    g_transform = (2 * mp.power(mp.pi, w) / mp.gamma(w) * beta
                   * (s - w - 1) / (2 * (s + w - 1)))
    c_series = mp.zeta(s - w) / mp.zeta(s + w)
    return g_transform * c_series


def kernel_invariants(omega):
    vals = [h_omega_mp(omega, mp.mpf("0.5")), k_omega_mp(omega, -1)]
    real_probe = h_omega_mp(omega, mp.mpf("2.25"))
    return {"h_below_one": str(vals[0]), "k_negative": str(vals[1]),
            "h_real": bool(mp.im(real_probe) == 0)}
