#!/usr/bin/env python3
"""Regenerate BFFT's checked-in hot lookup tables.

This script is not used by CMake or packaging. Deployed builds consume the
checked-in headers under src/detail/generated and do not need mpmath. To
regenerate the constants for development, install mpmath in your local Python
environment and run this script from the repository root:

    python3 -m pip install mpmath
    python3 tools/gen_phase_slope_tables.py
"""

from pathlib import Path

import mpmath as mp

mp.mp.dps = 100


def fmt_float(x):
    return mp.nstr(x, 17) + "f"


def fmt_double(x):
    return mp.nstr(x, 36)


def phase_table(leaves, q, typ):
    pi = mp.pi
    width = (pi / 4) / leaves
    leaf_lines = []
    for i in range(leaves):
        center = (mp.mpf(i) + mp.mpf("0.5")) * width
        c = mp.cos(center)
        s = mp.sin(center)
        if typ == "float":
            leaf_lines.append(f"    {{ {fmt_float(center)}, {fmt_float(c)}, {fmt_float(s)} }}")
        else:
            leaf_lines.append(f"    {{ {fmt_double(center)}, {fmt_double(c)}, {fmt_double(s)} }}")
    idxs = []
    for qi in range(q + 1):
        if qi == q:
            t = mp.mpf(1)
        else:
            t = (mp.mpf(qi) + mp.mpf("0.5")) / q
        theta = mp.atan(t)
        idx = int(mp.floor(theta / width))
        if idx < 0:
            idx = 0
        if idx >= leaves:
            idx = leaves - 1
        idxs.append(idx)
    return leaf_lines, idxs


def map_lines(idxs):
    lines = []
    for i in range(0, len(idxs), 16):
        chunk = ", ".join(str(v) for v in idxs[i:i+16])
        lines.append("    " + chunk)
    return lines


def write_phase_tables():
    parts = []
    parts.append("#pragma once\n")
    parts.append("// Generated by tools/gen_phase_slope_tables.py using mpmath with 100 decimal digits.\n")
    parts.append("// CMake and deployed builds consume this checked-in file directly; mpmath is not a build dependency.\n")
    parts.append("// Do not edit constants by hand.\n\n")
    for typ, leaves in [("float", 128), ("double", 256)]:
        leaf_lines, idxs = phase_table(leaves, 512, typ)
        parts.append(f"template<>\nstruct bruun_phase_slope_tables<{typ}, {leaves}, 512> {{\n")
        parts.append(f"    static constexpr int leaves_count = {leaves};\n")
        parts.append("    static constexpr int q_count = 512;\n")
        parts.append(f"    alignas(64) inline static constexpr bruun_phase_slope_leaf<{typ}> leaves[{leaves}] = {{\n")
        parts.append(",\n".join(leaf_lines))
        parts.append("\n    };\n")
        parts.append("    alignas(64) inline static constexpr std::uint8_t slope_to_leaf[513] = {\n")
        parts.append(",\n".join(map_lines(idxs)))
        parts.append("\n    };\n")
        parts.append("};\n\n")
    Path("src/detail/generated/bruun_phase_slope_tables.hpp").write_text("".join(parts))


def write_sincos_table():
    parts = []
    parts.append("#pragma once\n")
    parts.append("// Generated by tools/gen_phase_slope_tables.py using mpmath with 100 decimal digits.\n")
    parts.append("// CMake and deployed builds consume this checked-in file directly; mpmath is not a build dependency.\n")
    parts.append("// Do not edit constants by hand.\n\n")
    parts.append("alignas(64) inline constexpr bruun_sincos_sample bruun_sincos_table256[256] = {\n")
    for i in range(256):
        phase = 2 * mp.pi * i / 256
        s = mp.sin(phase)
        c = mp.cos(phase)
        comma = ","
        if i == 255:
            comma = ""
        parts.append(f"    {{ {fmt_double(s)}, {fmt_double(c)} }}{comma}\n")
    parts.append("};\n")
    Path("src/detail/generated/bruun_sincos_table256.hpp").write_text("".join(parts))


if __name__ == "__main__":
    write_phase_tables()
    write_sincos_table()
